// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd2rrDzAdM9zBi_D_9fSETEmf9Zvq8Jk8',
    appId: '1:504475863382:web:366653f201ad09fab5aef7',
    messagingSenderId: '504475863382',
    projectId: 'debts-manager-63f40',
    authDomain: 'debts-manager-63f40.firebaseapp.com',
    storageBucket: 'debts-manager-63f40.appspot.com',
    measurementId: 'G-TZVB6K8BT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6EIPI3zG3m42gBolAB_1rQKbkUHxOl0',
    appId: '1:504475863382:android:687bc371eecf2300b5aef7',
    messagingSenderId: '504475863382',
    projectId: 'debts-manager-63f40',
    storageBucket: 'debts-manager-63f40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkOVGz-odSWaGCBHzNgHeMcFZI-RX-qPY',
    appId: '1:504475863382:ios:146ede7c376f733fb5aef7',
    messagingSenderId: '504475863382',
    projectId: 'debts-manager-63f40',
    storageBucket: 'debts-manager-63f40.appspot.com',
    iosClientId: '504475863382-ck3j4ufi9apdtg3gto53phgfgit50erq.apps.googleusercontent.com',
    iosBundleId: 'com.example.debts',
  );
}
